version: "3.8"
services:
  app:
    build:
      context: .
      args:
        - UID=${DOCKER_UID:-1000}
        - GID=${DOCKER_GID:-1000}
    env_file: .env
    container_name: mechanics_bot
    command: sh -c "alembic upgrade head && cd ./src && python3 main.py"
    volumes:
      - .:/mechanics_bot
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: mechanics_db
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
