version: "3.8"
services:
  app:
    build:
      context: .
    env_file: .env
    container_name: mechanics_bot
    command: [ "./docker/app.sh" ]
    ports:
      - 8000:8000
    volumes:
      - .:/mechanics_bot
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db_app
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
