"""day off

Revision ID: 101a253af662
Revises: 96816d1aa74b
Create Date: 2024-07-30 10:44:34.946317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '101a253af662'
down_revision: Union[str, None] = '96816d1aa74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_off',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['master'], ['master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('day_off')
    # ### end Alembic commands ###
