"""schedule & department

Revision ID: 2c32111c7396
Revises: 667024192bc9
Create Date: 2024-06-07 11:08:51.248785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c32111c7396'
down_revision: Union[str, None] = '667024192bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master', sa.Integer(), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.Column('time_end', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['master'], ['master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('master', sa.Column('is_manager', sa.Boolean(), nullable=True))
    op.add_column('master', sa.Column('department', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'master', 'department', ['department'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'master', type_='foreignkey')
    op.drop_column('master', 'department')
    op.drop_column('master', 'is_manager')
    op.drop_table('schedule')
    op.drop_table('department')
    # ### end Alembic commands ###
