"""add category field to image

Revision ID: 5b57581f1f2d
Revises: 6a1c70bd986c
Create Date: 2025-09-19 11:04:22.141070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b57581f1f2d'
down_revision: Union[str, None] = '6a1c70bd986c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('category', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'category')
    # ### end Alembic commands ###
