"""gc_acception

Revision ID: 6a1c70bd986c
Revises: d54f1ed3744f
Create Date: 2025-08-05 14:13:50.981274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1c70bd986c'
down_revision: Union[str, None] = 'd54f1ed3744f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_cleaning_reaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master', sa.Integer(), nullable=True),
    sa.Column('general_cleaning', sa.Integer(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['general_cleaning'], ['general_cleaning.id'], ),
    sa.ForeignKeyConstraint(['master'], ['master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('general_cleaning_reaction')
    # ### end Alembic commands ###
