"""discipline violation

Revision ID: 95ec8f1d1e38
Revises: 101a253af662
Create Date: 2024-08-02 11:38:46.298852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ec8f1d1e38'
down_revision: Union[str, None] = '101a253af662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discipline_violation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['master'], ['master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discipline_violation')
    # ### end Alembic commands ###
