"""is_blocked

Revision ID: 96816d1aa74b
Revises: aafee1494f8c
Create Date: 2024-07-08 13:01:04.190296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96816d1aa74b'
down_revision: Union[str, None] = 'aafee1494f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master', 'is_blocked')
    # ### end Alembic commands ###
